### PR TITLE
Fixes and updates

### PR DESCRIPTION
**Pull request by iiFlamiinBlaze**
**Changes:**

- Bumped to ALPHA11
- bumped version
 - fixed formatting
-  fixed a few bugs
-  fixed class uses within whole plugin
-  adding gitignore

### CODE REVIEW

**Comment by ZeroDevOfficial** [comment]
did you test this commit?

if so I will push it

**Comment by ZeroDevOfficial** [comment]
Also I need to go back through this and recode the ui part and make it work with pmmp latest api

**Comment by iiFlamiinBlaze** [comment]
Yes, there should not be any issues since I didn't change anything major just a few class changes, formatting and minor stuff to make it work with ALPHA11. Have not tested it with 1.2.13 though.

**Comment by ZeroDevOfficial** [comment]
please test, I will push once its been tested

**Comment by iiFlamiinBlaze** [comment]
Works perfectly fine, tested it in 3.0.0-ALPHA12 release which is 1.2.13+

**Pull request merged**
